version: "3"

services:
    postgres:
        image: postgres
        container_name: my-postgres
        environment:
            POSTGRES_USER: adminpostgres
            POSTGRES_PASSWORD: 87654321
            POSTGRES_DB: my_db
        ports:
            - "5433:5432"

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
